version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: gofutsal-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kristofani-3560
      POSTGRES_DB: gofutsal
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: gofutsal-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: always   # â¬… TAMBAHKAN INI
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: gofutsal-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080

volumes:
  pgdata: