basePath: /
definitions:
  models.Booking:
    properties:
      booking_date:
        type: string
      court_id:
        type: integer
      customer_name:
        type: string
      end_time:
        type: string
      id:
        type: integer
      start_time:
        type: string
      total_price:
        type: integer
    type: object
  models.Court:
    properties:
      id:
        type: integer
      is_available:
        type: boolean
      location:
        type: string
      name:
        type: string
      price_per_hour:
        type: integer
    type: object
  models.User:
    properties:
      email:
        type: string
      id:
        type: integer
      password:
        type: string
      role:
        description: admin atau client
        example: client
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: henry@example.com
    name: Developer API Support
    url: https://github.com/HenryKristofani
  description: API untuk sistem booking lapangan futsal.
  termsOfService: http://swagger.io/terms/
  title: GoFutsal API
  version: "1.0"
paths:
  /api/bookings:
    get:
      description: Menampilkan semua data booking
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Booking'
            type: array
      summary: Get all bookings
      tags:
      - Bookings
    post:
      consumes:
      - application/json
      description: Membuat data booking baru
      parameters:
      - description: Booking Data
        in: body
        name: booking
        required: true
        schema:
          $ref: '#/definitions/models.Booking'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Booking'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create new booking
      tags:
      - Bookings
  /api/bookings/{id}:
    delete:
      description: Menghapus data booking berdasarkan ID
      parameters:
      - description: Booking ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete booking
      tags:
      - Bookings
    get:
      description: Menampilkan detail booking berdasarkan ID
      parameters:
      - description: Booking ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Booking'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get booking by ID
      tags:
      - Bookings
    put:
      consumes:
      - application/json
      description: Memperbarui data booking berdasarkan ID
      parameters:
      - description: Booking ID
        in: path
        name: id
        required: true
        type: integer
      - description: Booking Data
        in: body
        name: booking
        required: true
        schema:
          $ref: '#/definitions/models.Booking'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update booking
      tags:
      - Bookings
  /api/courts:
    get:
      description: Menampilkan semua lapangan futsal
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Court'
            type: array
      summary: Get all courts
      tags:
      - Courts
    post:
      consumes:
      - application/json
      description: Menambahkan data lapangan futsal baru
      parameters:
      - description: Court Data
        in: body
        name: court
        required: true
        schema:
          $ref: '#/definitions/models.Court'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Court'
      summary: Tambah lapangan baru
      tags:
      - Courts
  /api/courts/{id}:
    delete:
      description: Menghapus data lapangan futsal berdasarkan ID
      parameters:
      - description: Court ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete court
      tags:
      - Courts
    get:
      description: Menampilkan detail lapangan futsal berdasarkan ID
      parameters:
      - description: Court ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Court'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get court by ID
      tags:
      - Courts
    put:
      consumes:
      - application/json
      description: Memperbarui data lapangan futsal berdasarkan ID
      parameters:
      - description: Court ID
        in: path
        name: id
        required: true
        type: integer
      - description: Court Data
        in: body
        name: court
        required: true
        schema:
          $ref: '#/definitions/models.Court'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update court
      tags:
      - Courts
  /api/users:
    get:
      description: Menampilkan semua user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
      summary: Get all users
      tags:
      - Users
  /api/users/{id}:
    delete:
      description: Menghapus user berdasarkan ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete user
      tags:
      - Users
    get:
      description: Menampilkan user berdasarkan ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get user by ID
      tags:
      - Users
    put:
      consumes:
      - application/json
      description: Memperbarui data user berdasarkan ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: User Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update user
      tags:
      - Users
  /api/users/register:
    post:
      consumes:
      - application/json
      description: Membuat akun baru untuk client (role otomatis client)
      parameters:
      - description: User Data (tanpa role, role otomatis client)
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register akun client
      tags:
      - Users
swagger: "2.0"
